### ISSUE TITLE
Schema browser is not showing the parameters for stored procedures

### ISSUE THREAD

**Issue by mtaghiza** [sciserver/skyquery-all#1]
When inside the SDSSDR12 context and in the stored procedures object category, the menu for displaying and choosing the stored procedures works fine, but after choosing one procedure it does not show the parameters. And sometimes choosing one procedure does not bring up anything (only says "refreshing" and gets stuck).

I'm having this problem with the scalar and tabled-valued functions as well, but have no problem at all when viewing the definitions of the tables and views.

**Comment by mtaghiza** [comment]
Just realized that in the docs section is reads that stored procedures and functions are not supported yet :)

**Comment by dobos** [comment]
v1.2 supports it already.
