### ISSUE TITLE
API: Requesting a table with NULLs in it causes HTTP 502

### ISSUE THREAD

**Issue by dmedv** [sciserver/skyquery-all#13]
GET /skyquery/Api/V1/Data.svc/MyDB/MyTable?top=100 HTTP/1.1
Host: scitest02.pha.jhu.edu
X-Auth-Token: 78c43...

MyTable contents are:

```
id:int[4]  value:float[8]
1          0.1
2          0.2
3          0.3
4          NULL
```

This causes HTTP 502. The same table without NULLs works fine.

**Comment by dobos** [comment]
Confirmed, fixed in v1.2
