### ISSUE TITLE
Exporting a MyDB table throws HTTP 404

### ISSUE THREAD

**Issue by dmedv** [sciserver/skyquery-all#14]
Trying to export a MyDB table via the UI.

This request is generated and gives an HTTP 404 error page:
http://scitest02.pha.jhu.edu/skyquery/mydb/ExportTable.aspx?objid=Table|MYDB|MYDB_1889726769|mydb|MyTable

**Comment by dobos** [comment]
This is an issue in current production version too.

**Comment by dobos** [comment]
Fixed in v1.2
