### ISSUE TITLE
CSV table upload fails when table name contains a dash

### ISSUE THREAD

**Issue by mtaghiza** [sciserver/skyquery-all#15]
When I try giving the table the name "TestTableSciScript-R3", it returns an error saying: 
Syntax error: no understandable token found at (1,19)

**Comment by mtaghiza** [comment]
Trying this from the API, by the way.

**Comment by mtaghiza** [comment]
wait, it might be that the URL was not encoded properly...

**Comment by bonbons0220** [comment]
If this might be fixed in v1.10.0, please add this issue to that Project (see right hand hand on issue page).

**Comment by dobos** [comment]
The web form accepts the table name in properly escaped form, i.e. [import-test], just like it was in a SQL query, so I consider this a documentation issue, although I could escape the table name automatically. I'm checking the web API too.
