### ISSUE TITLE
GET method in API section seems to be not working

### ISSUE THREAD

**Issue by mtaghiza** [sciserver/skyquery-all#4]
I'm not sure if I'm doing it correctly.
Tried to get the first 10 rows of the Frame table of SDSSDR12:

http://scitest02.sdss.pha.jhu.edu/skyquery/Api/V1/Data.svc/SDSSDR12/Frame?top=10

(I'm already logged in with skyquery, not sure if I have to also specify a token for this)
The answer from google chrome is:

This webpage is not available
ERR_CONNECTION_TIMED_OUT

Have not tried the other methods yet.

**Comment by dobos** [comment]
This issue is fixed but v1.1 seems to return empty resultsets.

**Comment by dobos** [comment]
Fixed in v1.2, picks up correct database now.
